name: Build, Push and Scan Docker image with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Lowercase repository owner
        id: prep
        run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}  # Ensure you have this secret set up in your repository
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWER }}/chatgpt-app:latest

      - name: Log in to GHCR for Trivy
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}  # This should be the same username used for Docker login
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run Trivy vulnerability scanner on the Docker image
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: 'ghcr.io/${{ env.OWNER_LOWER }}/chatgpt-app:latest'
          format: 'table'
          exit-code: '1'  # Fail the job if vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        if: failure()  # Only upload if vulnerabilities were found
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-results.txt
