name: Build, Push and Scan Docker Image with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/eziodevio/chatgpt-app:latest
          push: true

      - name: Run Trivy vulnerability scanner on the Docker image
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: 'ghcr.io/eziodevio/chatgpt-app:latest'
          format: 'table'
          exit-code: '1'  # This will fail the job if any vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      - name: Logout from Docker
        if: always()
        run: docker logout ghcr.io

      - name: Upload Trivy scan results if vulnerabilities found
        if: failure()  # This step will execute if the Trivy scan step fails
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-results
          path: trivy-report.txt
