name: Build, Push and Scan Docker image

# Define when the workflow will run
on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request events to the main branch

# Define the jobs to be run
jobs:
  build-push-scan:
    runs-on: ubuntu-latest  # Specifies the runner environment
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner | lower }}/chatgpt-app:latest

      - name: Run Trivy vulnerability scanner on the Docker image
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner | lower }}/chatgpt-app:latest'
          format: 'table'
          exit-code: '0'  # Set to '0' to not fail the build even if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
