name: Build, Push and Scan Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/chatgpt-app:latest

    - name: Run Trivy vulnerability scanner on the Docker image
      uses: aquasecurity/trivy-action@0.0.8
      with:
        image-ref: 'ghcr.io/${{ github.repository_owner }}/chatgpt-app:latest'
        format: 'table'
        exit-code: '0' # Fails the step if vulnerabilities are found, use '0' to not fail
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

