
name: Build, Push and Scan Docker image with trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Convert repository owner to lowercase
      id: prep
      run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/chatgpt-app:latest

    - name: Run Trivy vulnerability scanner on the Docker image
      uses: aquasecurity/trivy-action@0.0.8
      with:
        image-ref: 'ghcr.io/${{ env.REPO_OWNER_LOWER }}/chatgpt-app:latest'
        format: 'table'
        exit-code: '1' # Set to '1' to fail the build if vulnerabilities are found
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results
      if: failure() # Only upload if the previous step failed
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.txt
