name: Build, Push and Scan Docker Image with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Convert repository owner to lowercase
        id: prep
        run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}  # Ensure this secret is correctly set in your GitHub repository
          password: ${{ secrets.GHCR_TOKEN }}   # Ensure this secret has the appropriate scopes
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWER }}/chatgpt-app:latest

      - name: Log in to GHCR for Trivy scanning
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run Trivy vulnerability scanner on the Docker image
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: 'ghcr.io/${{ env.OWNER_LOWER }}/chatgpt-app:latest'
          format: 'table'
          exit-code: '1'  # This will fail the job if any vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        if: failure()  # This step will execute if the Trivy scan step fails
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-results.txt

      - name: Logout from Docker
        if: always()  # Ensures that Docker is logged out from in all cases
        run: docker logout ghcr.io
