
jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner | lower }}/chatgpt-app:latest

    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.0.8
      with:
        image-ref: 'ghcr.io/${{ github.repository_owner | lower }}/chatgpt-app:latest'
        format: 'table'
        output: 'trivy-report.txt'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v2
      if: failure() # Only upload if the previous step failed (vulnerabilities found)
      with:
        name: trivy-report
        path: trivy-report.txt
